import type { Metadata } from "next";
import style from "./layout.module.css";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';

import Header from "@/components/shared/Header/Header";
import Footer from "@/components/shared/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="d-flex flex-column" style={{ minHeight: '100vh' }}>
        <Header></Header>
        <div className="mx-auto d-block bg-blue container py-4" style={{ flex: 1 }}>
          {children}
        </div>

        <Footer></Footer>
      </body>


    </html>
  );
}
